version: '3.8'

services:
  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
    - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents host node_modules from overwriting container's
    depends_on:
      - backend

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/__pycache__ # Prevents host __pycache__ from overwriting container's (optional)
    depends_on:
      - db
      - redis

  worker:
    build: ./backend
    command: celery -A app.worker.celery_app worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/__pycache__ # Prevents host __pycache__ from overwriting container's (optional)
    depends_on:
      - backend
      - redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coachsync
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
