"""add name phone address to user

Revision ID: 0d7e04bf401d
Revises: 789ba38f4149
Create Date: 2025-07-11 13:04:30.505542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7e04bf401d'
down_revision = '789ba38f4149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add name column as nullable first to handle existing users
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    
    # Update existing users with empty name to have a default value
    # This prevents issues when we later make it non-nullable
    op.execute("UPDATE users SET name = '' WHERE name IS NULL")
    
    # Now alter the column to be non-nullable
    op.alter_column('users', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
