"""add name phone address to user

Revision ID: 0d7e04bf401d
Revises: 789ba38f4149
Create Date: 2025-07-11 13:04:30.505542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7e04bf401d'
down_revision = '789ba38f4149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    # Removed all references to 'name' column
    # ### end Alembic commands ###
