"""split name into first and last name

Revision ID: 3f2e8a9b5c1d
Revises: 0d7e04bf401d
Create Date: 2025-07-14 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2e8a9b5c1d'
down_revision = '0d7e04bf401d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add first_name and last_name columns as nullable first
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    
    # Split existing names into first_name and last_name
    # This is a data migration step
    op.execute("""
        UPDATE users 
        SET first_name = CASE 
            WHEN POSITION(' ' IN name) > 0 
            THEN SUBSTRING(name FROM 1 FOR POSITION(' ' IN name) - 1)
            ELSE name
        END,
        last_name = CASE 
            WHEN POSITION(' ' IN name) > 0 
            THEN SUBSTRING(name FROM POSITION(' ' IN name) + 1)
            ELSE ''
        END
        WHERE name IS NOT NULL
    """)
    
    # Set default values for any NULL entries
    op.execute("UPDATE users SET first_name = '' WHERE first_name IS NULL")
    op.execute("UPDATE users SET last_name = '' WHERE last_name IS NULL")
    
    # Now make the columns non-nullable
    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'last_name', nullable=False)
    
    # Drop the old name column
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the name column
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    
    # Combine first_name and last_name back into name
    op.execute("""
        UPDATE users 
        SET name = TRIM(CONCAT(first_name, ' ', last_name))
    """)
    
    # Make name non-nullable and drop first_name, last_name
    op.alter_column('users', 'name', nullable=False)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
