"""split name into first and last name

Revision ID: 3f2e8a9b5c1d
Revises: 0d7e04bf401d
Create Date: 2025-07-14 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2e8a9b5c1d'
down_revision = '0d7e04bf401d'
branch_labels = None
depends_on = None


def upgrade():
    # Only ensure first_name and last_name are non-nullable
    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'last_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the name column
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    
    # Combine first_name and last_name back into name
    op.execute("""
        UPDATE users 
        SET name = TRIM(CONCAT(first_name, ' ', last_name))
    """)
    
    # Make name non-nullable and drop first_name, last_name
    op.alter_column('users', 'name', nullable=False)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
