"""fix meetings.user_idtype

Revision ID: f41a83ef8159
Revises: 20250718meetings
Create Date: 2025-07-18 22:34:01.143903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41a83ef8159'
down_revision = '20250718meetings'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
