"""split name into first and last name

Revision ID: 3f2e8a9b5c1d
Revises: 0d7e04bf401d
Create Date: 2025-07-14 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2e8a9b5c1d'
down_revision = '0d7e04bf401d'
branch_labels = None
depends_on = None


def upgrade():
    # Only ensure first_name and last_name are non-nullable
    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'last_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
    # Removed all references to 'name' column
    # ### end Alembic commands ###
